# This is a YAML-formatted pipeline.
# You can find more information on how to write pipelines at
# https://aka.ms/yaml

trigger:
  - push

jobs:
  - job: Deployment
    pool:
      vmImage: 'windows-latest'

    steps:
    - task: UseChocolatey@0
      inputs:
        packageType: 'exe'
        packageName: 'ASDeploymentWizard'

    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          # Set up the Deployment Wizard command
          $command = 'ASDeploymentWizard.exe /a "$(System.DefaultWorkingDirectory)\Model.asdatabase" /p "Partitions=True;Roles=True"'

          # Run the Deployment Wizard
          Invoke-Expression $command
