# This is a YAML-formatted pipeline.
# You can find more information on how to write pipelines at
# https://aka.ms/yaml

trigger:
  - push

jobs:
  - job: Deployment
    pool:
      vmImage: 'windows-latest'

    steps:
    - task: UseChocolatey@0
      inputs:
        packageType: 'exe'
        packageName: 'ASDeploymentWizard'
