# This is a YAML-formatted pipeline.
# You can find more information on how to write pipelines at
# https://aka.ms/yaml

trigger:
  - push

jobs:
  - job: Deployment
    pool:
      name: 'Default'

    steps:
    - task: NuGetToolInstaller@1
      inputs:
        command: 'install'
        packagesToInstall: 'ASDeploymentWizard'
        workingDirectory: '$(System.DefaultWorkingDirectory)'
        nugetConfigPath: '$(System.DefaultWorkingDirectory)\NuGet.config'

    - task: NuGetCommand@2
      inputs:
        targetType: 'inline'
        script: |
          # Set up the Deployment Wizard command
          $command = 'ASDeploymentWizard.exe /a "$(System.DefaultWorkingDirectory)\Model.asdatabase" /p "Partitions=True;Roles=True" /o'

          # Run the Deployment Wizard
          Invoke-Expression $command
    
    - task: NuGetCommand@2
      inputs:
        targetType: 'inline'
        script: |
          $deploymentOptionsFile = "$(System.DefaultWorkingDirectory)\Model.deploymentoptions"
          $parameters = "/p:Server=DESKTOP-9ADMLEA;Database=AdventureWorks2017;ProcessOption=DoNotProcess"
          & "$env:C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Microsoft SQL Server Tools 18\Analysis Services Deployment Wizard 18.lnk" /s:$deploymentOptionsFile $parameters
