# This is a YAML-formatted pipeline.
# You can find more information on how to write pipelines at
# https://aka.ms/yaml

trigger:
  - push

jobs:
  - job: Deployment
pool:
  name: Default

  steps:
    - task: CopyFiles@2
      displayName: 'Copy text file to local path'
      inputs:
        sourceFolder: '$(Agent.BuildDirectory)
        targetFolder: 'C:\Agents\vsts-agent-win-x64-2.213.2'
        includeContents: |
        /Model.asdatabase

    - task: NuGetToolInstaller@1
      inputs:
        command: 'install'
        packagesToInstall: 'ASDeploymentWizard'
        workingDirectory: '$(System.DefaultWorkingDirectory)'
        nugetConfigPath: '$(System.DefaultWorkingDirectory)\NuGet.config'

    - task: NuGetCommand@2
      inputs:
        targetType: 'inline'
        script: |
          # Set up the Deployment Wizard command
          $command = 'ASDeploymentWizard.exe /a "$(System.DefaultWorkingDirectory)\Model.asdatabase" /p "Partitions=True;Roles=True" /o'

          # Run the Deployment Wizard
          Invoke-Expression $command
      
    - task: NuGetCommand@2
      inputs:
        targetType: 'inline'
        script: |
         $parameters = "/p:Server=localhost;Database=AdventureWorks2017;ServerMode=Tabular;TabularModelFolder='';TabularModelName='';ProcessOption=DoNotProcess"
         & "$env:C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Microsoft SQL Server Tools 18\Analysis Services Deployment Wizard 18.lnk" /s:$deploymentOptionsFile $parameters